trigger:
  - azure-pipelines-withKubernetes
pool:
  vmImage: Ubuntu-16.04
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 10.x
    displayName: Install Node.js
  - script: |
      npm install
      npm run build
  - task: DockerCompose@0
    inputs:
      azureSubscriptionEndpoint: 'Azure for Students(e9122c58-941a-4646-8e7c-aadf7be91202)'
      azureContainerRegistry: '{"loginServer":"jamcamdockerkubernetes.azurecr.io", "id" : "/subscriptions/e9122c58-941a-4646-8e7c-aadf7be91202/resourceGroups/JamCamDockerKubernetes/providers/Microsoft.ContainerRegistry/registries/JamCamDockerKubernetes"}'
      action: 'Build services'
      includeLatestTag: true
  - task: DockerCompose@0
    inputs:
      azureSubscriptionEndpoint: 'Azure for Students(e9122c58-941a-4646-8e7c-aadf7be91202)'
      azureContainerRegistry: '{"loginServer":"jamcamdockerkubernetes.azurecr.io", "id" : "/subscriptions/e9122c58-941a-4646-8e7c-aadf7be91202/resourceGroups/JamCamDockerKubernetes/providers/Microsoft.ContainerRegistry/registries/JamCamDockerKubernetes"}'
      action: 'Push services'

